"""Build notation/index.html from the symbol glossaries (<dl class="symbols">) of every chapter page.

Run from the repository root after editing any glossary:  python tools/build_notation.py
The site itself has no build step; this only regenerates one static page.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHAPTERS = [
    ('brownian-motion', 'Chapter 1 · Brownian Motion'),
    ('variation', 'Chapter 2 · Variation & Martingales'),
    ('ito-integral', 'Chapter 3 · The Itô Integral'),
    ('ito-lemma', "Chapter 4 · Itô's Lemma"),
    ('sde', 'Chapter 5 · Stochastic Differential Equations'),
    ('applications', 'Chapter 6 · Applications'),
    ('diffusion-models', 'Chapter 7 · Diffusion Models'),
    ('beyond', 'Chapter 8 · Beyond Brownian Motion'),
]
SECTION = re.compile(r'<section id="([^"]+)" class="section">\s*<h2>(.*?)</h2>(.*?)</section>', re.S)
SYMBOLS = re.compile(r'<dl class="symbols">(.*?)</dl>', re.S)
ENTRY = re.compile(r'<dt>(.*?)</dt><dd>(.*?)</dd>', re.S)
TAGS = re.compile(r'<[^>]+>')


def rows():
    for slug, chapter in CHAPTERS:
        page = (ROOT / slug / 'index.html').read_text(encoding='utf-8')
        yield f'      <tr class="group"><th colspan="3">{chapter.replace("&", "&amp;")}</th></tr>'
        for sid, heading, body in SECTION.findall(page):
            dl = SYMBOLS.search(body)
            if not dl:
                continue
            title = ' '.join(TAGS.sub(' ', heading).split())
            link = f'<a href="../{slug}/index.html#{sid}">{title}</a>'
            for symbol, meaning in ENTRY.findall(dl.group(1)):
                yield f'      <tr><td>{symbol}</td><td>{meaning}</td><td>{link}</td></tr>'


PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Notation · Visual Stochastic Calculus</title>
<meta name="description" content="Every symbol used in Visual Stochastic Calculus, with its meaning in plain words and a link to the section that explains it.">
<link rel="canonical" href="https://nnm-psd.github.io/visual_stochastic_calculus/notation/">
<link rel="icon" href="../assets/favicon.svg" type="image/svg+xml">
<link rel="icon" href="../assets/favicon-32.png" sizes="32x32" type="image/png">
<link rel="apple-touch-icon" href="../assets/apple-touch-icon.png">
<meta name="theme-color" content="#fbfaf7">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Visual Stochastic Calculus">
<meta property="og:title" content="Notation · Visual Stochastic Calculus">
<meta property="og:description" content="Every symbol used in Visual Stochastic Calculus, with its meaning in plain words and a link to the section that explains it.">
<meta property="og:url" content="https://nnm-psd.github.io/visual_stochastic_calculus/notation/">
<meta property="og:image" content="https://nnm-psd.github.io/visual_stochastic_calculus/assets/og-image.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Visual Stochastic Calculus: a fan of Brownian paths with one highlighted in orange">
<meta name="twitter:card" content="summary_large_image">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">
<link rel="stylesheet" href="../assets/css/style.css">
<script>try {{ var t = localStorage.getItem('theme'); if (t) document.documentElement.dataset.theme = t; }} catch (e) {{}}</script>
</head>
<body>
<!-- Generated by tools/build_notation.py from the chapter glossaries. Edit those, then re-run. -->
<header class="site-header">
  <a href="../index.html">Visual Stochastic Calculus</a>
  <span class="links"><span>Notation</span><button type="button" class="theme-toggle">Dark mode</button></span>
</header>
<main>
  <h1>Notation</h1>
  <p class="lede">Every symbol used on this site, in the order it first appears, with the section that explains it. Use your browser's find (Ctrl+F or ⌘F) to look something up.</p>
  <table class="notation">
    <thead><tr><th>Symbol</th><th>Meaning</th><th>Explained in</th></tr></thead>
    <tbody>
{rows}
    </tbody>
  </table>
</main>
<script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js"></script>
<script>
  renderMathInElement(document.body, {{
    delimiters: [{{ left: '$$', right: '$$', display: true }}, {{ left: '$', right: '$', display: false }}]
  }});
</script>
<script src="../assets/js/theme.js"></script>
</body>
</html>
"""

if __name__ == '__main__':
    out = ROOT / 'notation' / 'index.html'
    out.parent.mkdir(exist_ok=True)
    body = list(rows())
    out.write_text(PAGE.format(rows='\n'.join(body)), encoding='utf-8')
    print(f'wrote {out.relative_to(ROOT)} with {sum(1 for r in body if "group" not in r)} entries')
